version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          SCYLLA_TEST_NODE: localhost:9042
      - image: scylladb/scylla:1.6.6

    working_directory: /go/src/github.com/dollarshaveclub/furan
    steps:
      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:9042 -timeout 1m

      - run: go get -v -t -d ./...
      - run: go test -v ./...
