# Default values for furan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 8
maxSurge: 25%
maxUnavailable: 25%
image:
  repository: quay.io/dollarshaveclub/furan
  tag: master
  pullPolicy: Always
  pullSecrets: image-pull-secrets

service:
  create: true
  type: ClusterIP

  httpInternalPort: 4000
  httpExternalPort: 4000

  grpcInternalPort: 4001
  grpcExternalPort: 4001

  httpHealthcheckPort: 4002
  httpHealthcheckPath: /health
  performanceProfilingPort: 4003

metrics_disabled: true

datadog:
  overrideDefaultTags: 'env:dev'
  statsdAddr: datadog.tools.svc.cluster.local:8125
  tracingAgentAddr: datadog.tools.svc.cluster.local:8126
  serviceName: furan-dqa

db:
  useConsulDiscovery: false
  nodes: "furan-scylladb"
  initialize: true
#kafkaBrokers: "furan-kafka-furan:9092"
kafkaBrokers: 'broker-40.kafka.ecommerce.dscinfra.com:9092,broker-50.kafka.ecommerce.dscinfra.com:9092,broker-60.kafka.ecommerce.dscinfra.com:9092' #testing

vault:
  useTokenAuth: true
  useK8sAuth: false
  addr: "http://furan-vault:8200"
  token: "root"

consulAddr: "furan-consul:8500"

ramdisk:
  enabled: false

dnsPolicy: ClusterFirst
dnsConfig: {}
