replicaCount: 1
createServiceAccount: false
createRole: false
serviceAccountName: furan-development
image:
  repository: 932427637498.dkr.ecr.us-west-2.amazonaws.com/furan
  tag: master
  pullPolicy: IfNotPresent
  pullSecrets: ""

run_migrations: false

annotations:

app:
  secrets_backend: "vault"
  secrets_mapping: "secret/{{ .ID }}"
  use_dev_cert: false

vault:
  address: "http://vault:8200"
  token: "root"
  use_token_auth: true
  use_k8s_auth: false
  k8sAuthPath: "auth/kube.shave.io" 
  agentInjector:
    enabled: false
    initFirst: true
    logLevel: info
  secretsPrefix: secret/services/furan/qa
  secrets:
  - path: db/uri
    key: value
  - path: db/credential_encryption_key
    key: value
  - path: github/token
    key: value
  - path: quay/token
    key: value

service:
  name: furan
  type: ClusterIP
  externalPort: 4000
  internalPort: 4000

ingress:
  enabled: false
  hosts:
    - furan.development.shave.io
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"

livenessProbe:
  initialDelaySeconds: 100
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

dnsPolicy: ClusterFirst
dnsConfig:
  options:
    - name: ndots
      value: "2"
    - name: attempts
      value: "5"
    - name: timeout
      value: "1"

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi